// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCosaV758B7sMzfYenzKx_sb-qXu_eMqnw',
    appId: '1:766997692958:web:5c8248c6467f02192d240f',
    messagingSenderId: '766997692958',
    projectId: 'chat-app-30521',
    authDomain: 'chat-app-30521.firebaseapp.com',
    storageBucket: 'chat-app-30521.firebasestorage.app',
    measurementId: 'G-DD106VD818',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_DaJGsQqT9IKjzOvgztdr_d2r_0io0Y4',
    appId: '1:766997692958:android:b441612b93be29342d240f',
    messagingSenderId: '766997692958',
    projectId: 'chat-app-30521',
    storageBucket: 'chat-app-30521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtmeXgygb2CxOCIBdJMx85WkRsVi1kcho',
    appId: '1:766997692958:ios:e42ff82e88d228b42d240f',
    messagingSenderId: '766997692958',
    projectId: 'chat-app-30521',
    storageBucket: 'chat-app-30521.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtmeXgygb2CxOCIBdJMx85WkRsVi1kcho',
    appId: '1:766997692958:ios:e42ff82e88d228b42d240f',
    messagingSenderId: '766997692958',
    projectId: 'chat-app-30521',
    storageBucket: 'chat-app-30521.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCosaV758B7sMzfYenzKx_sb-qXu_eMqnw',
    appId: '1:766997692958:web:639ad4dded1a63a82d240f',
    messagingSenderId: '766997692958',
    projectId: 'chat-app-30521',
    authDomain: 'chat-app-30521.firebaseapp.com',
    storageBucket: 'chat-app-30521.firebasestorage.app',
    measurementId: 'G-8CCBMX5FCY',
  );
}
